<?php 
	$product_id=$block->getConfigurableProductId();
	$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
	$configProduct = $objectManager->create('Magento\Catalog\Model\Product')->load($product_id);
	$_children = $configProduct->getTypeInstance()->getUsedProducts($configProduct);
    $variable = $objectManager->create('Magento\Variable\Model\Variable');
    $values = $variable->loadByCode('custom_package_accessories')->getPlainValue();
    $obj=(json_decode($values));
    $discount=$obj->discount;
?>
<div>
	<?php foreach ($_children as $_item): ?>
		<?php $_packagePrice=$_item->getFinalPrice()-($_item->getFinalPrice()*(0.3/100))?>

		<?php 
		 	$productStockObj = $objectManager->get('Magento\CatalogInventory\Api\StockRegistryInterface')->getStockItem($_item->getId());
            $status=round($productStockObj->getData('qty'));
        ?>
       <?php if ($status>0) : ?>
			<div class="associated-product"  product-price="<?php echo $_item->getFinalPrice()?>" product-id="<?php echo $_item->getId()?>"  custom-discount="<?php echo $_packagePrice ?>">
				<p id="dicountprice" style="display: none;"><?php echo number_format($_packagePrice,2, '.', ',')?></p>
				<p id="id" style="display: none;"><?php echo $_item->getId()?></p>
				<p id="sku" style="display: none;"><?php echo $_item->getSku()?></p>
				<div class="image">
					<?php 
						$imageBlock = $block->getLayout()->createBlock('Magento\Catalog\Block\Product\ListProduct');
						$productImage = $imageBlock->getImage($_item, 'category_page_grid'); 
						echo $productImage->toHtml(); 
					?>
				</div> 
				<div class="name-container"><div class="selected-icon">✔</div><div><?php echo $_item->getName()?></div></div>
				<div class="price"><?php echo '$'.number_format($_item->getFinalPrice(),2, '.', ',')?></div>
			</div>
		<?php endif; ?>
	<?php endforeach; ?>
</div>
